worker_processes 1;

events {
    worker_connections 1024;
}

http {
    sendfile on;

    upstream customer_service {
        server customer_service:8000;
    }

    upstream staff_service {
        server staff_service:8000;
    }

    upstream laptop_service {
        server laptop_service:8000;
    }

    upstream mobile_service {
        server mobile_service:8000;
    }

    server {
        listen 80;

        location /api/customer/ {
            proxy_pass http://customer_service/api/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /api/staff/ {
            proxy_pass http://staff_service/api/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /api/laptop/ {
            proxy_pass http://laptop_service/api/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /api/mobile/ {
            proxy_pass http://mobile_service/api/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}
