worker_processes 1;

events {
    worker_connections 1024;
}

http {
    sendfile on;

    upstream customer_service {
        server customer_service:8000;
    }

    upstream staff_service {
        server staff_service:8000;
    }

    upstream laptop_service {
        server laptop_service:8000;
    }

    upstream clothes_service {
        server clothes_service:8000;
    }

    upstream cart_service {
        server cart_service:8000;
    }

    server {
        listen 80;

        location /api/customer/ {
            proxy_pass http://customer_service/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /api/staff/ {
            proxy_pass http://staff_service/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /api/laptop/ {
            proxy_pass http://laptop_service/api/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /api/clothes/ {
            proxy_pass http://clothes_service/api/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /api/cart/ {
            proxy_pass http://cart_service/api/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}
